project '../AppFluMiOs.xcodeproj'

flutter_application_path = '../app_flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'AppFluMiOs' do
  install_all_flutter_pods(flutter_application_path)
end