// //BLA BLA BLA....
// Autogenerated from Pigeon (v10.1.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class PGNSendData;
@class PGNSenderStatus;
@class PGNReceiveData;

@interface PGNSendData : NSObject
+ (instancetype)makeWithData:(nullable NSString *)data;
@property(nonatomic, copy, nullable) NSString * data;
@end

@interface PGNSenderStatus : NSObject
+ (instancetype)makeWithResultSuccessful:(nullable NSNumber *)resultSuccessful
    hasError:(nullable NSNumber *)hasError
    error:(nullable NSString *)error;
@property(nonatomic, strong, nullable) NSNumber * resultSuccessful;
@property(nonatomic, strong, nullable) NSNumber * hasError;
@property(nonatomic, copy, nullable) NSString * error;
@end

@interface PGNReceiveData : NSObject
+ (instancetype)makeWithData:(nullable NSString *)data;
@property(nonatomic, copy, nullable) NSString * data;
@end

/// The codec used by PGNDataSender.
NSObject<FlutterMessageCodec> *PGNDataSenderGetCodec(void);

@protocol PGNDataSender
/// @return `nil` only when `error != nil`.
- (nullable PGNSenderStatus *)sendData:(PGNSendData *)data error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void PGNDataSenderSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PGNDataSender> *_Nullable api);

/// The codec used by PGNDataReceiver.
NSObject<FlutterMessageCodec> *PGNDataReceiverGetCodec(void);

@interface PGNDataReceiver : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)receiveData:(PGNReceiveData *)data completion:(void (^)(FlutterError *_Nullable))completion;
@end

NS_ASSUME_NONNULL_END
